### ISSUE TITLE
META Benchmarks

### ISSUE THREAD

**Issue by moul** [gnolang/benchmarks#1]
## Features

* [x] one folder per benchmark
* [ ] ways to generate graphs based on multiple runs

## Drivers

* [x] supernova
* [x] GitHub stargazers _(lack of raw data)_
* [ ] files map (https://githubnext.com/projects/repo-visualization/)
* [ ] ...
